/* Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.




*/


public class FindDifferentChar {
    
    
    
    
    
    
    
    
    
    
    // 最没有华彩的方法：用 HashMap
    //
    public char findTheDifference(String s, String t) {
        
        HashMap<Character, Integer> hashMap_S = new HashMap<Character, Integer>();
        
        for (char c : s.toCharArray())
        {
            if (hashMap_S.containsKey(c))
                hashMap_S.put(c, hashMap_S.get(c)+1);
            else
                hashMap_S.put(c, 1);
        }
        
        for (char c : t.toCharArray())
        {
            if (hashMap_S.containsKey(c) == false)
                return c;
            else
            {
                hashMap_S.put(c, hashMap_S.get(c)-1);
                
                if (hashMap_S.get(c) == -1)
                    return c;
            }
        }
        
        // input string incorrect
        return " ".toCharArray()[0];
    }
}
